version: "3"

services:
  ts-express-node:
    container_name: ts-express-node
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    ports: 
      - "8000:8000"
    command: >
      bash -c "npm install
      && npm run migrate
      && npm run dev"

  ts-express-postgres:
    image: postgres:16.2
    hostname: ts-express-postgres
    container_name: ts-express-postgres
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=${DB_USERNAME} 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: on-failure
    volumes:
      - ts-express-data:/var/lib/postgresql/data
      - ./database_dumps/:/docker-entrypoint-initdb.d/

volumes:
  ts-express-data: